<?php
include_once './objts/config.php';
include_once './objts/staff.php';
$cfg = new config();
$cfg->connect();
$fname = $_GET['fname'];
$lname = $_GET['lname'];
$cont = $_GET['cont'];
$gender = $_GET['gender'];
$uname = $_GET['uname'];
$upass = $_GET['upass'];
$rank = mysqli_real_escape_string($cfg->con, $_GET['rank']);
$stfid = $_GET['stfid'];
$dob = $_GET['sdob'];
$regno = $_GET['regno'];
$aqual = mysqli_real_escape_string($cfg->con, $_GET['aqual']);
$pqual = mysqli_real_escape_string($cfg->con, $_GET['pqual']);
$appdate = $_GET['appdate'];
$assdate = $_GET['assdate'];
$bank = $_GET['bankname'];
$accno = $_GET['accno'];
$ssnid = $_GET['ssnid'];

$stf = new Staff();
$stf->fname = $fname;
$stf->lname = $lname;
$stf->gender = $gender;
$stf->contact = $cont;
$stf->uname = $uname;
$stf->upass = md5($upass);
$stf->rank = $rank;
$stf->stfid = $stfid;
$stf->dob = $dob;
$stf->regno = $regno;
$stf->aqual = $aqual;
$stf->pqual = $pqual;
$stf->appdate = $appdate;
$stf->assdate = $assdate;
$stf->bankname = $bank;
$stf->accno = $accno;
$stf->ssnid = $ssnid;
$d = $stf->createstaff();
echo $d;